version: '3.7'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - mongo_network
networks:
  mongo_network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
