name: Run Spring Boot Tests on macOS

on:
  push:
    branches:
      - master  # Trigger on push to the main branch, change if needed
  pull_request:
    branches:
      - master  # Trigger on pull request to the main branch

jobs:
  test:
    runs-on: macos-latest  # macOS runner

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'  # Set to JDK 21
          distribution: 'zulu'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: /.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests with Maven
        run: mvn clean test

