name: Run Spring Boot Tests on macOS

on:
  push:
    branches:
      - main  # Trigger when pushing to the main branch (or any other branch of your choice)
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  test:
    runs-on: macos-latest  # This specifies the macOS runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'  # Set Java version for your Spring Boot project

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository  # Cache Maven dependencies to speed up builds
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and test with Maven
        run: mvn clean install -DskipTests=false  # Run tests using Maven (adjust for your needs)

      # Optional: Upload test results (JUnit XML or other formats)
      - name: Upload test results
        if: always()  # Run this even if tests fail
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: target/test-logs  # Path to test logs or reports
