name: Run Spring Boot Tests on macOS

on:
  push:
    branches:
      - master  # Trigger on push to the main branch, change if needed
  pull_request:
    branches:
      - master  # Trigger on pull request to the main branch

jobs:
  test:
    runs-on: macos-latest  # macOS runner

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'  # Set to JDK 21

      # Step 4: Build and run tests with Maven
      - name: Build and run tests with Maven
        run: mvn clean install -DskipTests=false  # Run Maven build and tests



      # Step 5 (Optional): Upload test results if necessary
      - name: Upload test results
        if: always()  # Ensure upload happens even if tests fail
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: target/test-logs  # Path to test logs (adjust as needed)
